# Generated by GPT-4

def unique(l: list):
    """Return sorted unique elements in a list

    >>> unique([5, 3, 5, 2, 3, 3, 9, 0, 123])
    [0, 2, 3, 5, 9, 123]
    """
    # Convert to a set to remove duplicates, then sort the result.
    # Note: this assumes elements are comparable (e.g., all numbers or all strings).
    return sorted(set(l))
