# Generated by GPT-4

def flip_case(string: str) -> str:
    """
    For a given string, flip lowercase characters to uppercase and uppercase to lowercase.

    >>> flip_case('Hello')
    'hELLO'
    >>> flip_case('')
    ''
    >>> flip_case('123! AbC')
    '123! aBc'
    """
    # Simple, correct, and handles Unicode letters:
    return string.swapcase()


# --- Optional: manual implementation (behaves the same) ---
def flip_case_manual(string: str) -> str:
    """
    Manual implementation without using str.swapcase().
    """
    result_chars = []
    for ch in string:
        if ch.islower():
            result_chars.append(ch.upper())
        elif ch.isupper():
            result_chars.append(ch.lower())
        else:
            result_chars.append(ch)
    return ''.join(result_chars)
