# Generated by gemini
def unique(l: list):
    """
    Return sorted unique elements in a list.

    The function uses a set to quickly filter out duplicate elements, 
    then uses the sorted() function to return the unique elements 
    in ascending order as a new list.

    >>> unique([5, 3, 5, 2, 3, 3, 9, 0, 123])
    [0, 2, 3, 5, 9, 123]
    """
    # Step 1: Convert the list to a set to get only unique elements.
    unique_elements = set(l)
    
    # Step 2: Sort the unique elements and return the result as a list.
    return sorted(unique_elements)