# Generated by gemini
def flip_case(string: str) -> str:
    """ For a given string, flip lowercase characters to uppercase and uppercase to lowercase.
    
    >>> flip_case('Hello')
    'hELLO'
    >>> flip_case('Python is Fun!')
    'pYTHON IS fUN!'
    >>> flip_case('12345')
    '12345'
    >>> flip_case('')
    ''
    """
    # The swapcase() method is a built-in string method in Python
    # that returns a copy of the string with uppercase characters
    # converted to lowercase and vice versa. It's the most direct
    # way to solve this problem.
    return string.swapcase()